---
title: blogdown_practice입니다 
author: JYH
date: '2020-07-13'
slug: blogdown-practice
output:
  html_document:
    highlight: zenburn
    theme: readable
    toc: yes
    fig_widgth: 3
    fig_height: 3
    toc_depth: 3
    toc_float: yes
categories:
  - R
tags:
  - R
  - tidyverse
  - 반갑습니다
  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=F, fig.align = "center", message=F, warning=F, fig.height = 3, cache=T, dpi = 300)
```


hello world!

```{r}
print('hello world!')

head(mtcars)

```

## stargazer

```{r fig.width = 3, fig.height = 3,  fig.align = "center"}
fit1<-lm(mpg ~ cyl *drat, mtcars)
plot(mtcars$cyl, mtcars$mpg)
abline(v=0,h=0)

```

```{r fig.cap = "scatterplot: cars", fig.width = 2, fig.height = 2, fig.align = "center"}
ggplot2:: ggplot(mtcars,aes(x=drat,y=mpg,group=cyl))+ geom_point()

```

## 유튜브 가능
```{r echo=FALSE }
blogdown::shortcode('youtube', 'vcVsjUh0ESk')
```


## 인스타그램 가능
```{r }
blogdown::shortcode('instagram','CBpbpW_HHnq')
```

```{r fig.cap = "scatterplot: cars", fig.width = 2, fig.height = 2,  fig.align = "center"}
x <-  rnorm(100)
y <-  x*2 + rnorm(100)
m <-  coef(lm(y ~ x))
plot(x,y)
abline(v=0, h=0, col='gray')
abline(m, col='blue')
```
> 안녕하세요 반갑습니다
>> 장연훈입니다.

~~찍찍~~
_기울이기_
__두껍게__


##


고생하셨습니다!

















